apiVersion: v1
kind: Secret
metadata:
  name: mcpspend-secrets
  labels:
    app.kubernetes.io/part-of: mcpspend
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL21jcHNwZW5kOm1jcHNwZW5kMTIzQG1jcHNwZW5kLXBvc3RncmVzOjU0MzIvbWNwc3BlbmQ=
  REDIS_URL: cmVkaXM6Ly9tY3BzcGVuZC1yZWRpczo2Mzc5
  JWT_SECRET: bWNwc3BlbmQtand0LXNlY3JldC04OTkxYzk4ZTMwMzFmOWMzY2I0OWNlZmE3YjJkYjAxMQ==
